name: Clone to Personal Repo for Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "navyoonj@gmail.com"

      - name: Clone Target Repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/plot-day/plot-client.git deploy-repo
          rsync -av --exclude=".git" --delete ./ deploy-repo/
          cd deploy-repo
          rm -rf .github
          git add .
          git commit -m "Auto-deploy from main branch" || echo "No changes to commit"

      - name: Push to Target Repository
        run: |
          cd deploy-repo
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/navynj/plot.git main -f
